language: 
  node_js
node_js:
 - "node"
services:
 - mongodb
cache:
  directories:
    - '$HOME/.npm'
env:
  global:
    - DATABASE_URL=mongodb://localhost:27017/posdb
before_install:
  - npm config set loglevel warn
install: npm ci
before_script:
  - sleep 15
  - mongo posdb --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
jobs:
  include:
    - stage: Unit and Integration tests
      script: npm test
after_script:
  echo 'All done :)'