language: 
  node_js
node_js:
 - "node"
services:
 - mongodb
env:
  global:
    - DATABASE_URL=mongodb://localhost:27017/posdb
    - CODECOV_TOKEN="63753f62-b3a7-417e-bfd4-a19f249d75c2"
before_install:
  - npm config set loglevel warn
install: 
  - npm ci
  - npm i -g codecov
before_script:
  - sleep 15
  - mongo posdb --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
jobs:
  include:
    - stage: Unit and Integration tests
      script: npm test