language: 
  node_js
node_js:
 - "node"
cache:
  directories:
    - '$HOME/.npm'
env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1
before_install:
  - npm config set loglevel warn
install: npm ci
jobs:
  include:
    - stage: Unit and Integration tests
      script: npm test